france = Country.find_by( name: "France" )

# French wine data. All wine regions and appellations.
france_wine_data_array = [
  # Alsace wine region:
  { "Alsace": 
    [ "Alsace",
      "Alsace Grand Cru",
      "Crémant d'Alsace"
    ] },
  # Beaujolais wine region: 
  { "Beaujolais": 
    [ "Beaujolais",
      "Beaujolais-Villages",
      "Brouilly",
      "Chénas",
      "Chiroubles",
      "Côte de Brouilly",
      "Fleurie",
      "Juliénas",
      "Morgon",
      "Moulin a vent",
      "Régnié",
      "Saint-Amour"
    ] },
  # Bordeaux wine region: 
  { "Bordeaux": 
    [ "Barsac",
      "Blaye",
      "Bordeaux",
      "Bordeaux clairet",
      "Bordeaux Côtes de Francs",
      "Bordeaux Haut-Benauge",
      "Bordeaux moelleux",
      "Bordeaux rosé",
      "Bordeaux sec",
      "Bordeaux supérieur",
      "Cadillac",
      "Canon Fronsac",
      "Cérons",
      "Côtes de Blaye",
      "Côtes de Bordeaux Saint-Macaire",
      "Côtes de Bourg",
      "Côtes de Castillon",
      "Crémant de Bordeaux",
      "Entre-Deux-Mers",
      "Entre-Deux-Mers-Haut-Benauge",
      "Fronsac",
      "Graves",
      "Graves de Vayres",
      "Graves Supérieures",
      "Haut-Médoc",
      "Lalande-de-Pomerol",
      "Listrac-Médoc",
      "Loupiac",
      "Lussac-Saint-Émilion",
      "Margaux",
      "Médoc",
      "Montagne Saint-Émilion",
      "Moulis-en-Médoc",
      "Néac",
      "Pauillac",
      "Pessac-Léognan",
      "Pomerol",
      "Premieres Côtes de Blaye",
      "Premieres Côtes de Bordeaux",
      "Puisseguin Saint-Émilion",
      "Saint-Émilion",
      "Saint-Émilion Grand Cru",
      "Saint-Estephe",
      "Saint-Georges Saint-Émilion",
      "Saint-Julien",
      "Sainte-Croix-du-Mont",  
      "Sainte-Foy-Bordeaux",
      "Sauternes"
    ] },
  # Bugey small wine regions outside any major ones
  { "Bugey": 
    [ "Bugey",
      "Roussette du Bugey"
    ]
  },
  # Burgundy wine region: 
  { "Burgundy": 
    [ "Aloxe-Corton",
      "Auxey-Duresses",
      "Bâtard-Montrachet",
      "Beaune",
      "Bienvenues-Bâtard-Montrachet",
      "Blagny",
      "Bonnes-Mares",
      "Bourgogne",
      "Bourgogne Aligoté",
      "Bourgogne Clairet",
      "Bourgogne Clairet Côte Chalonnaise",
      "Bourgogne Coulanges-la-Vineuse",
      "Bourgogne Côte Saint-Jacques",
      "Bourgogne Coulanges-la-Vineuse",
      "Bourgogne Côtes d'Auxerre",
      "Bourgogne Côtes du Couchois",
      "Bourgogne Epineuil",
      "Bourgogne Grand Ordinaire",
      "Bourgogne Hautes-côtes de Beaune",
      "Bourgogne Hautes-côtes de Nuits",
      "Bourgogne La Chapelle Notre-Dame",
      "Bourgogne le Chapitre",
      "Bourgogne Montrecul",
      "Bourgogne Mousseux",
      "Bourgogne Ordinaire",
      "Bourgogne Passe-tout-grains",
      "Bourgogne Vézelay",
      "Bourgogne rosé",
      "Bouzeron",
      "Chablis",
      "Chablis Grand Cru",
      "Chablis Premier Cru",
      "Chambertin",
      "Chambertin-Clos-de-Beze",
      "Chambolle-Musigny",
      "Chapelle-Chambertin",
      "Charlemagne",
      "Charmes-Chambertin",
      "Chassagne-Montrachet",
      "Chevalier-Montrachet",
      "Chorey-les-Beaune",
      "Clos des Lambrays",
      "Clos de la Roche",
      "Clos de Tart",
      "Clos de Vougeot",
      "Clos Saint-Denis",
      "Corton",
      "Corton-Charlemagne",
      "Côte de Beaune",
      "Côte de Beaune-Villages",
      "Côte de Nuits-villages",
      "Côtes du Forez",
      "Crémant de Bourgogne",
      "Criots-Bâtard-Montrachet",
      "Échezeaux",
      "Fixin",
      "Gevrey-Chambertin",
      "Givry",
      "Grands Échezeaux",
      "Griotte-Chambertin",
      "Irancy",
      "Ladoix",
      "La Grande Rue",
      "La Romanée",
      "La Tâche",
      "Latricieres-Chambertin",
      "Mâcon",
      "Mâcon supérieur",
      "Mâcon-villages",
      "Maranges",
      "Marsannay",
      "Mazis-Chambertin",
      "Mazoyeres-Chambertin",
      "Mercurey",
      "Meursault",
      "Montagny",
      "Monthelie",
      "Montrachet",
      "Morey-Saint-Denis",
      "Musigny",
      "Nuits-Saint-Georges",
      "Pernand-Vergelesses",
      "Petit Chablis",
      "Pommard",
      "Pouilly-Fuissé",
      "Pouilly-Loché",
      "Pouilly-Vinzelles",
      "Puligny-Montrachet",
      "Richebourg",
      "Romanée-Conti",
      "Romanée-Saint-Vivant",
      "Ruchottes-Chambertin",
      "Rully",
      "Saint-Aubin",
      "Saint-Bris",
      "Saint-Romain",
      "Saint-Véran",
      "Santenay",
      "Savigny-les-Beaune",
      "Tonnerre",
      "Vins Fins de la Côte de Nuits", 
      "Viré-Clessé",
      "Volnay",
      "Volnay Santenots",
      "Vosne-Romanée",
      "Vougeot"
    ] },
  # Champagne wine region:
  { "Champagne": 
    [ "Champagne",
      "Coteaux Champenois",
      "Rosé des Riceys"
    ] },
  # Corsica wine region:
  { "Corsica": 
    [ "Ajaccio",
      "Corse",
      "Patrimonio"
    ] },
  # Jura wine region:
  { "Jura": 
    [ "Arbois",
      "Château-Chalon",
      "Côtes du Jura",
      "Crémant du Jura",
      "L'Étoile"
    ] },
  # Languedoc-Roussillon wine region:
  { "Languedoc-Roussillon": 
    [ "Banyuls",
      "Banyuls Grand Cru",
      "Blanquette de Limoux",
      "Blanquette méthode ancestrale",
      "Cabardes",
      "Clairette de Bellegarde",
      "Clairette du Languedoc",
      "Collioure",
      "Corbieres",
      "Coteaux du Languedoc",
      "Côtes de la Malepere",
      "Côtes du Roussillon",
      "Côtes du Roussillon Villages",
      "Crémant de Limoux",
      "Faugeres",
      "Fitou",
      "Frontignan",
      "Grand Roussillon",
      "Limoux",
      "Maury",
      "Minervois",
      "Minervois-La Liviniere",
      "Muscat de Frontignan",
      "Muscat de Lunel",
      "Muscat de Mireval",
      "Muscat de Rivesaltes",
      "Muscat de Saint-Jean de Minervois",
      "Rivesaltes",
      "Saint-Chinian"
    ] },
  # Loire wine region: 
  { "Loire": 
    [ "Anjou",
      "Anjou-Coteaux de la Loire",
      "Anjou-Gamay",
      "Anjou mousseux",
      "Anjou Villages",
      "Anjou Villages Brissac",
      "Bonnezeaux",
      "Bourgueil",
      "Cabernet d'Anjou",
      "Cabernet de Saumur",
      "Chaume",
      "Cheverny",
      "Chinon",
      "Côte Roannaise",
      "Coteaux de l'Aubance",
      "Coteaux du Giennois",
      "Coteaux du Layon",
      "Coteaux du Loir",
      "Coteaux de Saumur",
      "Coteaux du Vendômois",
      "Cour-Cheverny",
      "Crémant de Loire",
      "Haut-Poitou",
      "Jasnieres",
      "Menetou-Salon",
      "Montlouis",
      "Muscadet",
      "Muscadet-Coteaux de la Loire",
      "Muscadet-Côtes de Grandlieu",
      "Muscadet-Sevre et Maine",
      "Orléans",
      "Orléans-Cléry",
      "Pouilly-Fumé",
      "Pouilly-sur-Loire",
      "Quarts de Chaume",
      "Quincy",
      "Reuilly",
      "Rosé d'Anjou",
      "Rosé de Loire",
      "Saint-Nicolas-de-Bourgueil",
      "Saint-Pourçain",
      "Sancerre",
      "Saumur",  
      "Saumur-Champigny",  
      "Saumur mousseux",
      "Savennières",  
      "Savennières-Coulée-de-Serrant",  
      "Savennières-Roche-aux-Moines",
      "Touraine",
      "Touraine-Amboise", 
      "Touraine-Azay-le-Rideau",  
      "Touraine-Mesland", 
      "Touraine Noble Joué",
      "Valençay",
      "Vouvray"
    ] },
  # Small wine area in Eastern France
  { "Lorraine": [ "Côtes de Toul" ] },
  # Small wine area around city of Lion
  { "Lyonnais": [ "Coteaux du Lyonnais" ] },
  # Provence wine region: 
  { "Provence": 
    [ "Bandol",
      "Bellet",
      "Cassis",
      "Coteaux d'Aix-en-Provence",
      "Coteaux de Pierrevert",
      "Coteaux Varois",
      "Côtes de Provence",
      "Les Baux-de-Provence",
      "Palette"
    ] },
  # Rhone wine region: 
  { "Rhône": 
    [ "Beaumes de Venise",
      "Château-Grillet",
      "Châteauneuf-du-Pape",
      "Châtillon-en-Diois",
      "Clairette de Die",
      "Condrieu",
      "Cornas",
      "Costières de Nîmes",
      "Côte-Rôtie",
      "Coteaux de Die",
      "Coteaux du Tricastin",
      "Côtes du Luberon",
      "Côtes du Rhône",
      "Côtes du Rhône Villages",
      "Côtes du Ventoux",
      "Côtes du Vivarais",
      "Crémant de Die",
      "Crozes-Hermitage",
      "Gigondas",
      "Hermitage",
      "Lirac",
      "Muscat de Beaumes-de-Venise",
      "Saint-Joseph",
      "Saint-Péray",
      "Tavel",
      "Vacqueyras",
      "Vinsobres"
    ] },
  # Savoie wine region:
  { "Savoie": 
    [ "Crépy",
      "Roussette de Savoie",
      "Seyssel",
      "Vin de Savoie"
    ] },
  # South-West of France:
  { "South-West France": 
    [ "Béarn",
      "Bergerac",
      "Bergerac sec",
      "Bergerac rosé",
      "Buzet",
      "Cahors",
      "Coteaux du Quercy",
      "Côtes de Bergerac",
      "Côtes de Bergerac Blanc",
      "Côtes de Duras",
      "Côtes de Millau",
      "Côtes de Montravel",
      "Côtes du Marmandais",
      "Fronton",
      "Gaillac",
      "Gaillac Premieres Côtess",
      "Haut-Montravel",
      "Irouléguy",
      "Jurançon",
      "Madiran",
      "Marcillac",
      "Monbazillac",
      "Montravel",
      "Pacherenc du Vic-Bilh",
      "Pacherenc du Vic-Bilh Sec",
      "Pécharmant",
      "Rosette",
      "Saint-Mont",
      "Saint-Sardos",
      "Saussignac",
      "Tursan",
      "Vins d'Entraygues et du Fel",
      "Vins d'Estaing"
    ] }
]

france_wine_data_array.each do |data_array|
  data_array.each do | region_name, appellations_array |
    wine_region = WineRegion.find_or_create_by!( { name: region_name, country: france} )  
    appellations_array.each do |appellation_name|
      Appellation.find_or_create_by!({ name: appellation_name, wine_region: wine_region})
    end
  end
end