# soda flavors seed data

soda_flavor_data = {
  none: {
    "almond",
    "apple",
    "apricot",
    "bacon",
    "birch beer",
    "blackberry",
    "bread",
    "brazil nut",
    "bubblegum",
    "buffalo wing",
    "burdock root",
    "celery",
    "cherry",
    "chocolate",
    "citron",
    "coffee",
    "cola", 
    "cranberry",
    "cream soda",
    "cucumber",
    "dandelion",
    "dirt",
    "gentiana",
    "ginger",
    "ginger ale",
    "ginger beer",
    "grape",
    "grapefruit",
    "guarana",
    "guava",
    "lemon",
    "lemonade",
    "lemon-lime",
    "lemon verbena/herbia luisa",
    "lime",
    "lychee",
    "malt",
    "mandarin orange",
    "mango",
    "mate",
    "melon",
    "mulberry",
    "nectarine",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "pineapple",
    "pomegranate",
    "raspberry",
    "ranch dressing",
    "root beer",
    "rye",
    "elderberry",
    "sarsaparilla",
    "strawberry",
    "tamarind",
    "watermelon",
    "white grape"
  },
  germany: {
    "Fassbrause" # german apple soda
  },
  norway: {
    "julebrus" # flavor unknown, christmas seasonal drink
  },
  russia: {
    "baikal" # cola flavored russian drink, used to be brand but now is generic
  }
]
